server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 81.69.226.40:8848
    gateway:
      routes: # 网关的配置
        - id: user-service # 路由的id唯一标识
          uri: lb://user-service # 路由的uri 目的地
          predicates: # 断言
            - Path=/user/** #判断路径是否是/user开头
          filters: # 过滤器
#            - AddRequestHeader=X-Request-Id,user-service # 添加请求头
        - id: order-service
          uri: lb://order-service
          predicates: # 断言
            - Path=/order/** #判断路径是否是/order开头
          filters: # 过滤器
#            - AddRequestHeader=X-Request-Id,order-service # 添加请求头
      default-filters: # 默认过滤器
        - AddRequestHeader=X-Request-Id,gateway # 添加请求头