server:
  port: 8083
spring:
  datasource:
    url: jdbc:postgresql://sh-tdcpg-ep-6a7wo2wi.sql.tencentcdb.com:28376/zeal?useSSL=false
    username: root
    password: Hewenxing4316
    driver-class-name: org.postgresql.Driver
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS