server:
  port: 8082
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://sh-tdcpg-ep-6a7wo2wi.sql.tencentcdb.com:28376/zeal?useSSL=false
    username: root
    password: Hewenxing4316
    driver-class-name: org.postgresql.Driver
  cloud:
    nacos:
      server-addr: 81.69.226.40:8848
      discovery:
#        cluster-name: shanghai
#        namespace: 778576cd-648f-4512-88d4-177e87f326d0
        # 非临时实例
        ephemeral: false
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#eureka:
#  client:
#    service-url: # eureka server url
#      defaultZone: http://localhost:10088/eureka/
user-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
      # 负载均衡策略
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#ribbon:
#  eager-load:
#    # 开启饥饿加载
#    enabled: true
#    clients:
feign:
#  client:
#    config:
#      default:
#        loggerLevel: FULL
  httpclient:
    enadbled: true
    connection-timeout: 5000
    max-connections: 20

#      - user-service # 饥饿加载的客户端